### ISSUE TITLE
Avoid CDN dependencies 

### ISSUE THREAD

**Issue by ahernandez-developer** [OSSPhilippines/v-animate-css#33]
Hello.

We are using this beautiful package from an intranet enviroment (no internet access).

This package is using animate.css cdn internally. (internet resource)

![image](https://user-images.githubusercontent.com/59542869/203424485-7b68f822-7cce-4af6-a7ae-7783293f46ed.png)

Unfortunately this behavior make the package useless in this kind of enviroments.

I suggest to include the animate.css files built in to prevent the cdn call to internet.

Or allow the pacakge to inject the animate.css from outside. Like vuetify does with mdi icons.

![image](https://user-images.githubusercontent.com/59542869/203424804-0ca89f5f-048f-4c3a-b9c4-79e93a06323d.png)

Cheers.

**Comment by jofftiquez** [comment]
This make sense @ahernandez-developer I think the latter would be a better solution. I'll consider it. Thank you.

**Comment by jofftiquez** [comment]
Hi, kindly check `v-animate-css@0.0.6`, the demo and docs are also updated now. Thanks
