### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by Cholowao** [OSSPhilippines/v-animate-css#39]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

https://ossphilippines.github.io/v-animate-css/

**Comment by jofftiquez** [comment]
Thanks for this!

**Comment by jofftiquez** [comment]
Link replaced with https://v-animate-css.ossph.org/
